[workspace]
resolver = "3"
members = ["lib", "client", "server", "keygen"]


[workspace.package]
version = "0.2.5"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Ilya Nixan <nixan@nerdy.pro>"]
repository = "https://github.com/orosu-ci/orosu"
homepage = "https://orosu.dev"