[package]
name = "orosu"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/server/main.rs"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.7", features = ["ws"] }
clap = { version = "4.5.53", features = ["derive", "env"] }
dotenvy = "0.15.7"
mime_guess = "2.0.5"
rust-embed = "8.9.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
tower-http = { version = "0.6.7", features = ["trace"] }
serde_json = "1.0.145"
derivative = "2.2.0"
argon2 = "0.5.3"
password-hash = "0.5.0"
notify = "8.2.0"
uuid = { version = "1.18.1", features = ["serde", "v4"] }
chrono = { version = "0.4.42", features = ["serde"] }
axum-client-ip = "1.1.3"
tower-layer = "0.3.3"
tower-service = "0.3.3"
axum-extra = { version = "0.12.2", features = ["cookie"] }
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
tokio-tungstenite = "0.28.0"
futures-util = "0.3.31"
bytes = "1.11.0"
base64 = "0.22.1"
rand = "0.9.2"
serde-saphyr = "0.0.11"
